import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSQLite1788160827656 implements MigrationInterface {
    name = 'InitialSQLite1788160827656'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "tenants" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar(255) NOT NULL, "slug" varchar(100) NOT NULL, "code" varchar(9) NOT NULL, "plan" varchar NOT NULL DEFAULT ('free'), "settings" text DEFAULT ('{}'), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "deleted_at" datetime, CONSTRAINT "UQ_2310ecc5cb8be427097154b18fc" UNIQUE ("slug"), CONSTRAINT "UQ_3021c18db2b363ae9324c826c5a" UNIQUE ("code"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" varchar PRIMARY KEY NOT NULL, "tenant_id" varchar, "email" varchar(50) NOT NULL, "password_hash" varchar(255), "first_name" varchar(20), "last_name" varchar(20), "avatar_url" text, "is_email_verified" boolean NOT NULL DEFAULT (0), "verification_token" varchar(255), "verification_otp" varchar(6), "verification_expires_at" datetime, "workspace_role" varchar NOT NULL DEFAULT ('member'), "isActive" boolean DEFAULT (1), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "deleted_at" datetime)`);
        await queryRunner.query(`CREATE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8f438641d1d4a8af79152fc84a" ON "users" ("verification_token") WHERE verification_token IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e9f4c2efab52114c4e99e28efb" ON "users" ("tenant_id", "email") `);
        await queryRunner.query(`CREATE TABLE "sessions" ("id" varchar PRIMARY KEY NOT NULL, "user_id" varchar NOT NULL, "status" varchar(10) NOT NULL DEFAULT ('ACTIVE'), "device_name" varchar(255), "browser" varchar(100), "operating_system" varchar(100), "ip_address" varchar, "user_agent" text, "revoked_at" datetime, "last_used_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "expires_at" datetime NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE TABLE "transactions" ("id" varchar PRIMARY KEY NOT NULL, "payment_id" varchar NOT NULL, "user_id" varchar NOT NULL, "tenant_id" varchar, "type" varchar NOT NULL, "amount" bigint NOT NULL, "currency" varchar(3) NOT NULL, "description" text, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_e9acc6efa76de013e8c1553ed2" ON "transactions" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "payments" ("id" varchar PRIMARY KEY NOT NULL, "user_id" varchar NOT NULL, "order_id" varchar NOT NULL, "amount" bigint NOT NULL, "currency" varchar(3) NOT NULL, "status" varchar NOT NULL DEFAULT ('PENDING'), "paymentMethod" varchar NOT NULL, "razorpay_payment_id" varchar(255), "razorpay_signature" varchar(512), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "REL_b2f7b823a21562eeca20e72b00" UNIQUE ("order_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e7d1bec5311dcddd28c50547e8" ON "payments" ("razorpay_payment_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c2a89b63635ae2b4cc76f17a08" ON "payments" ("user_id", "status") `);
        await queryRunner.query(`CREATE TABLE "orders" ("id" varchar PRIMARY KEY NOT NULL, "user_id" varchar NOT NULL, "tenant_id" varchar, "amount" bigint NOT NULL, "currency" varchar(3) NOT NULL, "status" varchar NOT NULL DEFAULT ('PENDING'), "razorpay_order_id" varchar(255), "plan" varchar(100), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_a922b820eeef29ac1c6800e826" ON "orders" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a493914f314964159c6fb6fe5f" ON "orders" ("razorpay_order_id") `);
        await queryRunner.query(`CREATE TABLE "subscriptions" ("id" varchar PRIMARY KEY NOT NULL, "user_id" varchar NOT NULL, "tenant_id" varchar, "plan" varchar NOT NULL, "status" varchar NOT NULL DEFAULT ('ACTIVE'), "current_period_start" datetime NOT NULL, "current_period_end" datetime NOT NULL, "cancel_at_period_end" boolean NOT NULL DEFAULT (0), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_d0a95ef8a28188364c546eb65c" ON "subscriptions" ("user_id") `);
        await queryRunner.query(`DROP INDEX "IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP INDEX "IDX_8f438641d1d4a8af79152fc84a"`);
        await queryRunner.query(`DROP INDEX "IDX_e9f4c2efab52114c4e99e28efb"`);
        await queryRunner.query(`CREATE TABLE "temporary_users" ("id" varchar PRIMARY KEY NOT NULL, "tenant_id" varchar, "email" varchar(50) NOT NULL, "password_hash" varchar(255), "first_name" varchar(20), "last_name" varchar(20), "avatar_url" text, "is_email_verified" boolean NOT NULL DEFAULT (0), "verification_token" varchar(255), "verification_otp" varchar(6), "verification_expires_at" datetime, "workspace_role" varchar NOT NULL DEFAULT ('member'), "isActive" boolean DEFAULT (1), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "deleted_at" datetime, CONSTRAINT "FK_109638590074998bb72a2f2cf08" FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_users"("id", "tenant_id", "email", "password_hash", "first_name", "last_name", "avatar_url", "is_email_verified", "verification_token", "verification_otp", "verification_expires_at", "workspace_role", "isActive", "created_at", "updated_at", "deleted_at") SELECT "id", "tenant_id", "email", "password_hash", "first_name", "last_name", "avatar_url", "is_email_verified", "verification_token", "verification_otp", "verification_expires_at", "workspace_role", "isActive", "created_at", "updated_at", "deleted_at" FROM "users"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`ALTER TABLE "temporary_users" RENAME TO "users"`);
        await queryRunner.query(`CREATE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8f438641d1d4a8af79152fc84a" ON "users" ("verification_token") WHERE verification_token IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e9f4c2efab52114c4e99e28efb" ON "users" ("tenant_id", "email") `);
        await queryRunner.query(`CREATE TABLE "temporary_sessions" ("id" varchar PRIMARY KEY NOT NULL, "user_id" varchar NOT NULL, "status" varchar(10) NOT NULL DEFAULT ('ACTIVE'), "device_name" varchar(255), "browser" varchar(100), "operating_system" varchar(100), "ip_address" varchar, "user_agent" text, "revoked_at" datetime, "last_used_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "expires_at" datetime NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_085d540d9f418cfbdc7bd55bb19" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_sessions"("id", "user_id", "status", "device_name", "browser", "operating_system", "ip_address", "user_agent", "revoked_at", "last_used_at", "expires_at", "created_at") SELECT "id", "user_id", "status", "device_name", "browser", "operating_system", "ip_address", "user_agent", "revoked_at", "last_used_at", "expires_at", "created_at" FROM "sessions"`);
        await queryRunner.query(`DROP TABLE "sessions"`);
        await queryRunner.query(`ALTER TABLE "temporary_sessions" RENAME TO "sessions"`);
        await queryRunner.query(`DROP INDEX "IDX_e9acc6efa76de013e8c1553ed2"`);
        await queryRunner.query(`CREATE TABLE "temporary_transactions" ("id" varchar PRIMARY KEY NOT NULL, "payment_id" varchar NOT NULL, "user_id" varchar NOT NULL, "tenant_id" varchar, "type" varchar NOT NULL, "amount" bigint NOT NULL, "currency" varchar(3) NOT NULL, "description" text, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_464da95dc8a05470b2b158d4df6" FOREIGN KEY ("payment_id") REFERENCES "payments" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_e9acc6efa76de013e8c1553ed2b" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_4f27188c6c1d993bc76aeddcded" FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_transactions"("id", "payment_id", "user_id", "tenant_id", "type", "amount", "currency", "description", "created_at", "updated_at") SELECT "id", "payment_id", "user_id", "tenant_id", "type", "amount", "currency", "description", "created_at", "updated_at" FROM "transactions"`);
        await queryRunner.query(`DROP TABLE "transactions"`);
        await queryRunner.query(`ALTER TABLE "temporary_transactions" RENAME TO "transactions"`);
        await queryRunner.query(`CREATE INDEX "IDX_e9acc6efa76de013e8c1553ed2" ON "transactions" ("user_id") `);
        await queryRunner.query(`DROP INDEX "IDX_e7d1bec5311dcddd28c50547e8"`);
        await queryRunner.query(`DROP INDEX "IDX_c2a89b63635ae2b4cc76f17a08"`);
        await queryRunner.query(`CREATE TABLE "temporary_payments" ("id" varchar PRIMARY KEY NOT NULL, "user_id" varchar NOT NULL, "order_id" varchar NOT NULL, "amount" bigint NOT NULL, "currency" varchar(3) NOT NULL, "status" varchar NOT NULL DEFAULT ('PENDING'), "paymentMethod" varchar NOT NULL, "razorpay_payment_id" varchar(255), "razorpay_signature" varchar(512), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "REL_b2f7b823a21562eeca20e72b00" UNIQUE ("order_id"), CONSTRAINT "FK_427785468fb7d2733f59e7d7d39" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_b2f7b823a21562eeca20e72b006" FOREIGN KEY ("order_id") REFERENCES "orders" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_payments"("id", "user_id", "order_id", "amount", "currency", "status", "paymentMethod", "razorpay_payment_id", "razorpay_signature", "created_at", "updated_at") SELECT "id", "user_id", "order_id", "amount", "currency", "status", "paymentMethod", "razorpay_payment_id", "razorpay_signature", "created_at", "updated_at" FROM "payments"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`ALTER TABLE "temporary_payments" RENAME TO "payments"`);
        await queryRunner.query(`CREATE INDEX "IDX_e7d1bec5311dcddd28c50547e8" ON "payments" ("razorpay_payment_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c2a89b63635ae2b4cc76f17a08" ON "payments" ("user_id", "status") `);
        await queryRunner.query(`DROP INDEX "IDX_a922b820eeef29ac1c6800e826"`);
        await queryRunner.query(`DROP INDEX "IDX_a493914f314964159c6fb6fe5f"`);
        await queryRunner.query(`CREATE TABLE "temporary_orders" ("id" varchar PRIMARY KEY NOT NULL, "user_id" varchar NOT NULL, "tenant_id" varchar, "amount" bigint NOT NULL, "currency" varchar(3) NOT NULL, "status" varchar NOT NULL DEFAULT ('PENDING'), "razorpay_order_id" varchar(255), "plan" varchar(100), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_a922b820eeef29ac1c6800e826a" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_527dd6efd5f3402f729c6b3e826" FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_orders"("id", "user_id", "tenant_id", "amount", "currency", "status", "razorpay_order_id", "plan", "created_at", "updated_at") SELECT "id", "user_id", "tenant_id", "amount", "currency", "status", "razorpay_order_id", "plan", "created_at", "updated_at" FROM "orders"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`ALTER TABLE "temporary_orders" RENAME TO "orders"`);
        await queryRunner.query(`CREATE INDEX "IDX_a922b820eeef29ac1c6800e826" ON "orders" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a493914f314964159c6fb6fe5f" ON "orders" ("razorpay_order_id") `);
        await queryRunner.query(`DROP INDEX "IDX_d0a95ef8a28188364c546eb65c"`);
        await queryRunner.query(`CREATE TABLE "temporary_subscriptions" ("id" varchar PRIMARY KEY NOT NULL, "user_id" varchar NOT NULL, "tenant_id" varchar, "plan" varchar NOT NULL, "status" varchar NOT NULL DEFAULT ('ACTIVE'), "current_period_start" datetime NOT NULL, "current_period_end" datetime NOT NULL, "cancel_at_period_end" boolean NOT NULL DEFAULT (0), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_d0a95ef8a28188364c546eb65c1" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_f6ac03431c311ccb8bbd7d3af18" FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_subscriptions"("id", "user_id", "tenant_id", "plan", "status", "current_period_start", "current_period_end", "cancel_at_period_end", "created_at", "updated_at") SELECT "id", "user_id", "tenant_id", "plan", "status", "current_period_start", "current_period_end", "cancel_at_period_end", "created_at", "updated_at" FROM "subscriptions"`);
        await queryRunner.query(`DROP TABLE "subscriptions"`);
        await queryRunner.query(`ALTER TABLE "temporary_subscriptions" RENAME TO "subscriptions"`);
        await queryRunner.query(`CREATE INDEX "IDX_d0a95ef8a28188364c546eb65c" ON "subscriptions" ("user_id") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "IDX_d0a95ef8a28188364c546eb65c"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" RENAME TO "temporary_subscriptions"`);
        await queryRunner.query(`CREATE TABLE "subscriptions" ("id" varchar PRIMARY KEY NOT NULL, "user_id" varchar NOT NULL, "tenant_id" varchar, "plan" varchar NOT NULL, "status" varchar NOT NULL DEFAULT ('ACTIVE'), "current_period_start" datetime NOT NULL, "current_period_end" datetime NOT NULL, "cancel_at_period_end" boolean NOT NULL DEFAULT (0), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "subscriptions"("id", "user_id", "tenant_id", "plan", "status", "current_period_start", "current_period_end", "cancel_at_period_end", "created_at", "updated_at") SELECT "id", "user_id", "tenant_id", "plan", "status", "current_period_start", "current_period_end", "cancel_at_period_end", "created_at", "updated_at" FROM "temporary_subscriptions"`);
        await queryRunner.query(`DROP TABLE "temporary_subscriptions"`);
        await queryRunner.query(`CREATE INDEX "IDX_d0a95ef8a28188364c546eb65c" ON "subscriptions" ("user_id") `);
        await queryRunner.query(`DROP INDEX "IDX_a493914f314964159c6fb6fe5f"`);
        await queryRunner.query(`DROP INDEX "IDX_a922b820eeef29ac1c6800e826"`);
        await queryRunner.query(`ALTER TABLE "orders" RENAME TO "temporary_orders"`);
        await queryRunner.query(`CREATE TABLE "orders" ("id" varchar PRIMARY KEY NOT NULL, "user_id" varchar NOT NULL, "tenant_id" varchar, "amount" bigint NOT NULL, "currency" varchar(3) NOT NULL, "status" varchar NOT NULL DEFAULT ('PENDING'), "razorpay_order_id" varchar(255), "plan" varchar(100), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "orders"("id", "user_id", "tenant_id", "amount", "currency", "status", "razorpay_order_id", "plan", "created_at", "updated_at") SELECT "id", "user_id", "tenant_id", "amount", "currency", "status", "razorpay_order_id", "plan", "created_at", "updated_at" FROM "temporary_orders"`);
        await queryRunner.query(`DROP TABLE "temporary_orders"`);
        await queryRunner.query(`CREATE INDEX "IDX_a493914f314964159c6fb6fe5f" ON "orders" ("razorpay_order_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a922b820eeef29ac1c6800e826" ON "orders" ("user_id") `);
        await queryRunner.query(`DROP INDEX "IDX_c2a89b63635ae2b4cc76f17a08"`);
        await queryRunner.query(`DROP INDEX "IDX_e7d1bec5311dcddd28c50547e8"`);
        await queryRunner.query(`ALTER TABLE "payments" RENAME TO "temporary_payments"`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" varchar PRIMARY KEY NOT NULL, "user_id" varchar NOT NULL, "order_id" varchar NOT NULL, "amount" bigint NOT NULL, "currency" varchar(3) NOT NULL, "status" varchar NOT NULL DEFAULT ('PENDING'), "paymentMethod" varchar NOT NULL, "razorpay_payment_id" varchar(255), "razorpay_signature" varchar(512), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "REL_b2f7b823a21562eeca20e72b00" UNIQUE ("order_id"))`);
        await queryRunner.query(`INSERT INTO "payments"("id", "user_id", "order_id", "amount", "currency", "status", "paymentMethod", "razorpay_payment_id", "razorpay_signature", "created_at", "updated_at") SELECT "id", "user_id", "order_id", "amount", "currency", "status", "paymentMethod", "razorpay_payment_id", "razorpay_signature", "created_at", "updated_at" FROM "temporary_payments"`);
        await queryRunner.query(`DROP TABLE "temporary_payments"`);
        await queryRunner.query(`CREATE INDEX "IDX_c2a89b63635ae2b4cc76f17a08" ON "payments" ("user_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_e7d1bec5311dcddd28c50547e8" ON "payments" ("razorpay_payment_id") `);
        await queryRunner.query(`DROP INDEX "IDX_e9acc6efa76de013e8c1553ed2"`);
        await queryRunner.query(`ALTER TABLE "transactions" RENAME TO "temporary_transactions"`);
        await queryRunner.query(`CREATE TABLE "transactions" ("id" varchar PRIMARY KEY NOT NULL, "payment_id" varchar NOT NULL, "user_id" varchar NOT NULL, "tenant_id" varchar, "type" varchar NOT NULL, "amount" bigint NOT NULL, "currency" varchar(3) NOT NULL, "description" text, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "transactions"("id", "payment_id", "user_id", "tenant_id", "type", "amount", "currency", "description", "created_at", "updated_at") SELECT "id", "payment_id", "user_id", "tenant_id", "type", "amount", "currency", "description", "created_at", "updated_at" FROM "temporary_transactions"`);
        await queryRunner.query(`DROP TABLE "temporary_transactions"`);
        await queryRunner.query(`CREATE INDEX "IDX_e9acc6efa76de013e8c1553ed2" ON "transactions" ("user_id") `);
        await queryRunner.query(`ALTER TABLE "sessions" RENAME TO "temporary_sessions"`);
        await queryRunner.query(`CREATE TABLE "sessions" ("id" varchar PRIMARY KEY NOT NULL, "user_id" varchar NOT NULL, "status" varchar(10) NOT NULL DEFAULT ('ACTIVE'), "device_name" varchar(255), "browser" varchar(100), "operating_system" varchar(100), "ip_address" varchar, "user_agent" text, "revoked_at" datetime, "last_used_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "expires_at" datetime NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "sessions"("id", "user_id", "status", "device_name", "browser", "operating_system", "ip_address", "user_agent", "revoked_at", "last_used_at", "expires_at", "created_at") SELECT "id", "user_id", "status", "device_name", "browser", "operating_system", "ip_address", "user_agent", "revoked_at", "last_used_at", "expires_at", "created_at" FROM "temporary_sessions"`);
        await queryRunner.query(`DROP TABLE "temporary_sessions"`);
        await queryRunner.query(`DROP INDEX "IDX_e9f4c2efab52114c4e99e28efb"`);
        await queryRunner.query(`DROP INDEX "IDX_8f438641d1d4a8af79152fc84a"`);
        await queryRunner.query(`DROP INDEX "IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`ALTER TABLE "users" RENAME TO "temporary_users"`);
        await queryRunner.query(`CREATE TABLE "users" ("id" varchar PRIMARY KEY NOT NULL, "tenant_id" varchar, "email" varchar(50) NOT NULL, "password_hash" varchar(255), "first_name" varchar(20), "last_name" varchar(20), "avatar_url" text, "is_email_verified" boolean NOT NULL DEFAULT (0), "verification_token" varchar(255), "verification_otp" varchar(6), "verification_expires_at" datetime, "workspace_role" varchar NOT NULL DEFAULT ('member'), "isActive" boolean DEFAULT (1), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "deleted_at" datetime)`);
        await queryRunner.query(`INSERT INTO "users"("id", "tenant_id", "email", "password_hash", "first_name", "last_name", "avatar_url", "is_email_verified", "verification_token", "verification_otp", "verification_expires_at", "workspace_role", "isActive", "created_at", "updated_at", "deleted_at") SELECT "id", "tenant_id", "email", "password_hash", "first_name", "last_name", "avatar_url", "is_email_verified", "verification_token", "verification_otp", "verification_expires_at", "workspace_role", "isActive", "created_at", "updated_at", "deleted_at" FROM "temporary_users"`);
        await queryRunner.query(`DROP TABLE "temporary_users"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e9f4c2efab52114c4e99e28efb" ON "users" ("tenant_id", "email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8f438641d1d4a8af79152fc84a" ON "users" ("verification_token") WHERE verification_token IS NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`DROP INDEX "IDX_d0a95ef8a28188364c546eb65c"`);
        await queryRunner.query(`DROP TABLE "subscriptions"`);
        await queryRunner.query(`DROP INDEX "IDX_a493914f314964159c6fb6fe5f"`);
        await queryRunner.query(`DROP INDEX "IDX_a922b820eeef29ac1c6800e826"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP INDEX "IDX_c2a89b63635ae2b4cc76f17a08"`);
        await queryRunner.query(`DROP INDEX "IDX_e7d1bec5311dcddd28c50547e8"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP INDEX "IDX_e9acc6efa76de013e8c1553ed2"`);
        await queryRunner.query(`DROP TABLE "transactions"`);
        await queryRunner.query(`DROP TABLE "sessions"`);
        await queryRunner.query(`DROP INDEX "IDX_e9f4c2efab52114c4e99e28efb"`);
        await queryRunner.query(`DROP INDEX "IDX_8f438641d1d4a8af79152fc84a"`);
        await queryRunner.query(`DROP INDEX "IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "tenants"`);
    }

}
