export const CONSOLE_COLORS = {
  RESET: '\x1b[0m',
  RED: '\x1b[31m',
  GREEN: '\x1b[32m',
  YELLOW: '\x1b[33m',
  BLUE: '\x1b[34m',
  MAGENTA: '\x1b[35m',
  CYAN: '\x1b[36m',
  WHITE: '\x1b[37m',
};

export const MODULE_PREFIXES = {
  REDIS: `${CONSOLE_COLORS.MAGENTA}[Redis]${CONSOLE_COLORS.RESET}`,
  RABBITMQ: `${CONSOLE_COLORS.CYAN}[RabbitMQ]${CONSOLE_COLORS.RESET}`,
  AUTH: `${CONSOLE_COLORS.BLUE}[Auth]${CONSOLE_COLORS.RESET}`,
  USERS: `${CONSOLE_COLORS.GREEN}[Users]${CONSOLE_COLORS.RESET}`,
  TENANTS: `${CONSOLE_COLORS.YELLOW}[Tenants]${CONSOLE_COLORS.RESET}`,
  PAYMENTS: `${CONSOLE_COLORS.MAGENTA}[Payments]${CONSOLE_COLORS.RESET}`,
  SUBSCRIPTIONS: `${CONSOLE_COLORS.CYAN}[Subscriptions]${CONSOLE_COLORS.RESET}`,
  ORDERS: `${CONSOLE_COLORS.WHITE}[Orders]${CONSOLE_COLORS.RESET}`,
  TRANSACTIONS: `${CONSOLE_COLORS.RED}[Transactions]${CONSOLE_COLORS.RESET}`,
  SESSION: `${CONSOLE_COLORS.BLUE}[Session]${CONSOLE_COLORS.RESET}`,
  DATABASE: `${CONSOLE_COLORS.MAGENTA}[Database]${CONSOLE_COLORS.RESET}`,
  HTTP: `${CONSOLE_COLORS.CYAN}[HTTP]${CONSOLE_COLORS.RESET}`,
};
